host: 0.0.0.0
port: 5200
database:
  uri: sqlite:///sample.db
aws:
  access-key: "hxmR3l6SuN6lAjwd0sDs"
  secret-key: "1FaFnK3GKgGiOnNCwMvAbIbnSA8bUNVi"
  bucket: "catalog"
  region: "us-east-1"
  url: "http://localhost:9000"

argon:
  memory-cost: 102400
  salt-length: 16
  hash-length: 16
  parallelism: 8
  time-cost: 2
  variant: 2