CREATE TABLE IF NOT EXISTS recovery_tb (
    id BIGSERIAL PRIMARY KEY,
	user_id BIGINT NOT NULL,
	due_date  TIMESTAMP NOT NULL,
	otp VARCHAR NOT NULL,
	reference VARCHAR NOT NULL,
	idx BIGSERIAL NOT NULL UNIQUE,
	CONSTRAINT user_fkey FOREIGN KEY (user_id) REFERENCES user_tb(id) ON DELETE CASCADE
);
